### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by kushwaha-suraj** [adrianhajdin/project_travel_advisor#55]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\suraj\Downloads\project_travel_advisor-master\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.0

**Comment by kushwaha-suraj** [comment]
set NODE_OPTIONS=--openssl-legacy-provider
